sudo: false
language:
  - node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
install:
  - npm install
script:
  - npm run test -- --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
