export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';

export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const TASK_ERROR = 'TASK_ERROR';
export const FETCH_TASKS = 'FETCH_TASKS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
